version: '3.5'
services:
  app:
    build: .
    ports:
      - '5000:5000'
    environment:
      FLASK_GA4_ID: '328048912'
      FLASK_GA4_CREDENTIALS_PATH: './key.json'
      FLASK_CORS_CORS_ALLOW_HEADERS: 'User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type'
      FLASK_CORS_METHODS: 'GET, OPTIONS'
      FLASK_CORS_ORIGINS: '*'
    working_dir: /app
    volumes:
       - .:/app
    command: gunicorn -b :5000 -w 4 'server:app'
